### ISSUE TITLE
rosppm/ppm_io.h: No such file or directory

### ISSUE THREAD

**Issue by Villotadavid** [gokoreas/rosppm#10]
Hi there!
Thank you for releasing the code!

I am having some problem will flashing the arduino.
May be the problem comes from the installation commands.
I follow the github commands, however when I reach the last line 
`catkin_make --pkg usb2ppm_ros`
that yields:
`Packages "usb2ppm_ros" not found in the workspace`
so I correct it by changing usb2ppm_ros into rosppm that apparently works fine.
However when I try to flash the arduino, I get the following error:
`rosppm/ppm_io.h: No such file or directory`
I tried the solution given in the issue [https://github.com/Jaeyoung-Lim/rosppm/issues/6](url)
but it doesn´t work.
So I cannot flase the arduino.

Thank you in advance

**Comment by Jaeyoung-Lim** [comment]
Sorry for the misleading documentation.

1. The file you are trying to build with catkin_make is not related to the arduino image. It is a ROS node that you can run on your ROS enabled device. You can flash the arduino image without building the package with the file named `rosppm_arduino.ino` 

2. The `rosppm/ppm_io.h` should be generated as a custom mesage file. Could you may be try with
```
catkin clean
catkin build rosppm
```

**Comment by Villotadavid** [comment]
It worked fine!
After doing what you told me I needed to source the directory.
Thank you very much.

**Comment by Jaeyoung-Lim** [comment]
@Villotadavid glad that it worked out. I will update the documentation accordingly
